# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
env:
  DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
  KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
  HOST_NAME: ${{secrets.HOST_NAME}}
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rsync_the_jobs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: cloning the repo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Authenticating
        run: |
          mkdir -p ~/.ssh
          echo "${KNOWN_HOSTS}" > ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" > ~/.ssh/rsync_key
          echo "Host awsvm\nHostname ${HOST_NAME}\nUser ubuntu\nport 22\nIdentityFile ~/.ssh/rsync_key\nPreferredAuthentications publickey" > ~/.ssh/config
          chmod 700 ~/.ssh/rsync_key
        
      - name: Deploy
        run: rsync -avz . awsvm:~/actions
